services:
  - type: web
    name: ML_PIPELINE_PROJECT
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run api_server.py --server.port $PORT --server.headless true